apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-remediate-applier
  namespace: auto-remediate
  labels:
    app.kubernetes.io/part-of: auto-remediate
    app.kubernetes.io/component: rbac
    auto-remediate/identity: applier
